---
# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# https://github.com/getsops/sops?tab=readme-ov-file#using-sops-yaml-conf-to-select-kms-pgp-and-age-for-new-files

creation_rules:
  - path_regex: src/sdavids-.+\.tex$
    age: >-
      age1x9hzzkvxzncvp6gfl8njxcffesvhp5hcgmfsypwkhmss4ghaldvqngpt3s
