// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids-latex-german-job-application
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: CV of Sebastian Davids
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 4
:toc-placement!:
:hide-uri-scheme:
:source-highlighter: rouge
:rouge-style: github
// Refs:
:docker-install-url: https://docs.docker.com/install/
:jetbrains-latex-install-url: https://plugins.jetbrains.com/plugin/9473-texify-idea
:mactex-install-url: https://www.tug.org/mactex/mactex-download.html
:sops-install-url: https://github.com/getsops/sops/releases
:texifier-install-url: https://www.texifier.com
:texlive-install-url: https://www.tug.org/texlive/acquire-netinstall.html
:texmaker-install-url: https://www.xm1math.net/texmaker/download.html
:texstudio-install-url: https://www.texstudio.org/#download
:vs-code-latex-install-url: https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-google-style: https://github.com/google/gts

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:important-caption: :heavy_exclamation_mark:
:note-caption: :information_source:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids-latex-german-job-application[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids-latex-german-job-application[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids-latex-german-job-application[GitHub last commit]
endif::[]

toc::[]

This repository contains LaTeX classes, commands, and environments for a German job application.

== License

Apache License, Version 2.0 (link:LICENSES/Apache-2.0.txt[Apache-2.0.txt] or {uri-apache-license}).

== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT.md[Code of Conduct].

== Development Environment Setup

[IMPORTANT]
====
After initializing this repository you need to install the Git hooks via:

[source,shell]
----
$ git config core.hooksPath .githooks
----
====

[#dev-env-installation]
=== Installation

[#age]
==== age

===== Linux

[source,shell]
----
$ sudo apt-get install age
----

===== Mac

[source,shell]
----
$ brew install age
----

[#docker]
==== Docker

Install {docker-install-url}[Docker].

[#exiftool]
==== exiftool

===== Linux

[source,shell]
----
$ sudo apt-get install exiftool
----

===== Mac

[source,shell]
----
$ brew install exiftool
----

[#qpdf]
==== qpdf

===== Linux

[source,shell]
----
$ sudo apt-get install qpdf
----

===== Mac

[source,shell]
----
$ brew install qpdf
----

[#shellcheck]
==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

==== shfmt

===== Linux

[source,shell]
----
$ sudo apt-get install shfmt
----

===== Mac

[source,shell]
----
$ brew install shfmt
----

[#sops]
==== sops

===== Linux

Install {sops-install-url}[sops].

===== Mac

[source,shell]
----
$ brew install sops
----

[#yamllint]
==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----

[#ide]
=== IDE

See link:CODING_STYLE.adoc#ide-configuration[IDE Configuration].

[#latex-tools]
=== LaTeX Tools

==== LaTeX Editor

If you need a graphical editor you might want to use:

* {texifier-install-url}[Texifier] (paid)
* {texmaker-install-url}[Texmaker] (free)
* {texstudio-install-url}[TeXstudio] (free)

or IDE extensions:

* {jetbrains-latex-install-url}[JetBrains IDEs] (free)
* {vs-code-latex-install-url}[VS Code] (free)

==== LaTeX Toolchain

[NOTE]
====
The link:scripts/latex_pdf_build.sh[build script] does not need a locally installed LaTeX toolchain.
====

===== Linux

Install {texlive-install-url}[TeX Live] (around 5.5GB).

===== Mac

Install {mactex-install-url}[MacTeX] (around 5.7GB).
