# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-latex-german-job-application"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-latex-german-job-application"
