# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-latex-german-job-application"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-latex-german-job-application"

[[annotations]]
path = "src/fonts/Lora-**"
SPDX-FileCopyrightText = "© 2011 The Lora Project Authors (https://github.com/cyrealtype/Lora-Cyrillic)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/fonts/Nunito-**"
SPDX-FileCopyrightText = "© 2014 The Nunito Project Authors (https://github.com/googlefonts/nunito)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "docs/asciidoc/images/*.png",
  "examples/*.pdf",
]
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"
